# Generated by Django 4.2.7 on 2024-04-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='backend.task'),
        ),
    ]
