# Generated by Django 4.2.7 on 2024-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_activity_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(default='Productivity', max_length=100, null=True),
        ),
    ]
