# Generated by Django 4.2.7 on 2024-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_activity_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-uploaded']},
        ),
        migrations.AddField(
            model_name='activity',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
