# Generated by Django 4.2.7 on 2024-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_activity_options_activity_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_dark',
        ),
        migrations.AddField(
            model_name='client',
            name='preferences',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
