# Generated by Django 4.2.7 on 2024-04-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_client_is_dark_client_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='flag',
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
