# Generated by Django 4.2.7 on 2024-05-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_group_participants_alter_progress_success_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='success_rate',
            field=models.IntegerField(null=True),
        ),
    ]
