# Generated by Django 4.2.7 on 2024-06-06 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
    ]
