# Generated by Django 4.2.7 on 2024-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.CharField(default='1.png', max_length=1250),
        ),
    ]
